const SKILLS = [
    'TypeScript',
    'JavaScript',
    'HTML',
    'CSS',
    'Swift',
    'PostgreSQL',
    'PHP',
    'C#',
    'Bash Shell Scripting',
    'React-Native',
    'React.js',
    'Redux',
    'Next.js',
    'Jest',
    'GraphQL',
    'Express.js',
    'Svelte',
    'Fastify',
    'Electron',
    'Node.js',
    'Yarn',
    'NPM',
    'XCode',
    'Git',
    'GitHub',
    'GitLab',
    'Visual Studio Code',
    'ESLint',
    'Prettier',
    'Firebase',
    'Google Cloud',
    'CircleCI',
    'Vercel',
    'Heroku',
    'curl',
    'StoryBook',
    'Jira',
    'Slack',
    'Blender',
    'Unity'
]

export default SKILLS