import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.introduction}>
          <div className={styles.photoContainer}>
            <Image  className={styles.photo} src="/images/novas-photo.jpg" alt="me" width="200" height="200" />
          </div>

          <h1 className={styles.title}>
            Hi, I am

            <br />

            <div className={styles.titleName}>
              Reynald Prabha Nova
            </div>
          </h1>
        </section>

        <section className={styles.anotherSection}>
          <h1>
            {'Careers & Projects'}
          </h1>
        </section>

        <section className={styles.anotherSection}>
          <h1>
            Skills
          </h1>
        </section>

        <section className={styles.anotherSection}>
          <h1>
            Contact
          </h1>
        </section>
      </main>
    </>
  )
}

export default Home
